spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: placeholder-google-client-id
            client-secret: placeholder-google-client-secret
            scope: profile, email
          github:
            client-id: placeholder-github-client-id
            client-secret: placeholder-github-client-secret
            scope: user:email, read:user
